version: '3.6'

services:

  crowd:
    image: atlassian/crowd:4.2.3
    ports:
      - "8095:8095"
    environment:
      - JVM_MINIMUM_MEMORY=2g
      - JVM_MAXIMUM_MEMORY=2g
      #- ATL_PROXY_NAME=www.313.co.kr
      #- ATL_PROXY_PORT=8094
      #- ATL_TOMCAT_SCHEME=http
    extra_hosts:
      - "313.co.kr:192.168.25.46"
      - "db.313.co.kr:192.168.25.40"
      - "nas.313.co.kr:192.168.25.42"
      - "www.313.co.kr:192.168.25.42"
      - "ubuntu.313.co.kr:192.168.25.46"
    volumes:
      - crowdApp:/var/atlassian/application-data/crowd
      - crowdLib:/opt/atlassian/crowd/apache-tomcat/lib
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mysql
    deploy: &auth-deploy
      mode: replicated
      replicas: 1
    networks: &auth-network
      - authnetwork
    logging: &auth-logging
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

# create database keycloakdb character set utf8 collate utf8_bin;
# GRANT ALL PRIVILEGES ON keycloakdb.* TO 'mysqluser'@'%';
# create database crowddb character set utf8 collate utf8_bin;
# GRANT ALL PRIVILEGES ON keycloakdb.* TO 'mysqluser'@'%';
# flush privileges;
  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloakdb
      - DB_USER=mysqluser
      - DB_PASSWORD=mysqluserpassword
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=qwe123
      - JDBC_PARAMS=serverTimezone=UTC&connectTimeout=30000
    ports:
      - "8585:8080"
    depends_on:
      - mysql
      - crowd
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/deployments
      - keycloakThemes:/opt/jboss/keycloak/themes
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy: *auth-deploy
    networks: *auth-network
    logging: *auth-logging

  mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqluserpassword
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
      - TZ=Asia/Seoul
    command: >-
      --user=mysql
      --port=3306
      --pid-file=/data/dbfiles/mysql.pid
      --datadir=/data/dbfiles
      --tmpdir=/data/dbfiles
      --long_query_time=1
      --lc-messages=en_US
      --event_scheduler=1
      --default_password_lifetime=0
      --log_timestamps=SYSTEM
      --explicit_defaults_for_timestamp=on
      --character-set-client-handshake=FALSE
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-external-locking
      --skip-name-resolve
      --transaction-isolation=READ-COMMITTED
      --query_cache_size=0
      --query_cache_limit=0
      --bind-address=0.0.0.0
      --max_connect_errors=9999999
      --max_connections=1024
      --table_open_cache=2048
      --max_allowed_packet=64M
      --performance_schema
      --local_infile=0
      --secure_file_priv=''
      --log_error_verbosity=1
      --tmp_table_size=128M
      --max_heap_table_size=1G
      --server-id=1
      --default-storage-engine=InnoDB
      --thread_cache_size=64
      --binlog_cache_size=1M
      --back_log=1024
      --ft_min_word_len=4
      --read_buffer_size=2M
      --read_rnd_buffer_size=16M
      --sort_buffer_size=2M
      --join_buffer_size=2M
      --skip-external-locking
      --key_buffer_size=128M
      --bulk_insert_buffer_size=64M
      --myisam_sort_buffer_size=128M
      --myisam_max_sort_file_size=512M
      --myisam_repair_threads=1
      --innodb_checksum_algorithm=NONE
      --innodb_buffer_pool_size=32G
      --innodb_file_per_table
      --innodb_data_file_path=ibdata1:1G;ibdata2:1G;ibdata3:1G:autoextend
      --innodb_data_home_dir=/data/dbfiles/
      --innodb_write_io_threads=2
      --innodb_read_io_threads=8
      --innodb_fast_shutdown
      --innodb_autoinc_lock_mode=1
      --innodb_thread_concurrency=4
      --innodb_flush_log_at_trx_commit=1
      --innodb_max_dirty_pages_pct=90
      --innodb_flush_method=0_DIRECT
      --innodb_doublewrite=0
      --innodb_lock_wait_timeout=120
      --innodb_open_files=1024
      --innodb_log_buffer_size=16M
      --innodb_log_file_size=256M
      --innodb_lof_files_in_group=3
      --innodb_log_group_home_dir=/data/logs/redolog
      --binlog_cache_size=1M
      --log-bin=/data/logs/binlog/mysql-log-bin
      --log_bin_trust_function_creators=1
      --expire_logs_days=7
      --max_binlog_size=100M
      --binlog_format=row
      --binlog_row_image=minimal
      --binlog_checksum=none
      --sync_binlog=1
      --gtid_mode=off
      --enforce_gtid_consistency=off
      --binlog-ignore-db=performance_schema
      --binlog-ignore-db=information_schema
      --binlog-ignore-db=sys
      --log_slave_updates=1
    volumes:
      - mysql:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy: *auth-deploy
    networks: *auth-network
    logging: *auth-logging

volumes:

  crowdApp:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/auth/crowdApp"

  crowdLib:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/auth/crowdLib"

  keycloak:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/auth/keycloak"

  keycloakThemes:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/auth/keycloakThemes"

  mysql:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/auth/mysql"

networks:
  authnetwork:
    attachable: true
