version: '3.6'

services:

  mysqldb:
    image: mysql:5.7.32
    hostname: mysqldb
    command: 
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=www313cokr
      - MYSQL_ROOT_PASSWORD=qwe123!@#
      - TZ=Asia/Seoul
    networks: &mysqldb-network
      - mysqldb_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
    volumes:
      - mysqldbVolume:/var/lib/mysql
      - mysqlTmpVolume:/tmp
      - mysqlLogVolume:/var/log/mysql
    configs:
      - source: my.cnf
        target: /etc/mysql/my.cnf

configs:
  my.cnf:
    file: ./my.cnf

volumes:
  mysqldbVolume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/mysql"

  mysqlTmpVolume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/mysqlTmp"

  mysqlLogVolume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/mysqlLog"

networks:
  mysqldb_network:
    attachable: true

